# Generate this file content for my project.
steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/"project-id"/gemini-app/my-app:${SHORT_SHA}', '.'] # Put own  ProjectID

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/"project-id"/gemini-app/my-app:${SHORT_SHA}'] # Put own  ProjectID

# Store images to google artifactory
images:
  - 'us-central1-docker.pkg.dev/"project-id"/gemini-app/my-app:${SHORT_SHA}' # Put own  ProjectID
